### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by osteele** [olinlibrary/loanbot#16]
```
$ python tests.py
E
======================================================================
ERROR: test_find_tools_in_message (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 27, in test_find_tools_in_message
    conversation_handler.find_tools_in_message(test_message_1), [{
  File "/Users/osteele/code/htl/loanbot/conversationHandler.py", line 44, in find_tools_in_message
    for alt_name in tool['alternate_names']:
KeyError: 'alternate_names'
```

**Comment by osteele** [comment]
Comment cd0293f2 added `tool['alternate_names']` to the code, but not to the test data.
